### ISSUE TITLE
Readfish with Guppy 6

### ISSUE THREAD

**Issue by hasindu2008** [LooseLab/readfish#170]
Is it possible to get readfish working on Guppy 6?

**Comment by mattloose** [comment]
Hi Hasindu,

It will be....

We're testing with Guppy 6 and will release a branch with compatibility soon. There are a couple of changes between 5 and 6 which need to be handled well.

Will post here when it's available.

**Comment by alexomics** [comment]
Guppy v5.1.0 and v6.0.0 introduce the use of IPC sockets on linux and
OSX see: https://community.nanoporetech.com/posts/guppy-v6-0-0-release

This requires a change in configuration in the TOML files, where `host'
is given this must point to the guppy IPC address e.g.:

```TOML
[caller_settings]
config_name = "dna_r9.4.1_450bps_fast"
host = "ipc:///tmp/.guppy"
port = 5555
```

This is a temporary fix and I intend to make a single compatible interface when I have time
