### ISSUE TITLE
which branch of readfish is suitable?

### ISSUE THREAD

**Issue by Flower9618** [LooseLab/readfish#215]
Hi, thank you very much for sharing this very useful tool.

I found many branches of readfish, like issue187, guppy_6, guppy_6_minknow_5. I wonder which branch of readfish is suitable for minknow core version 5.3.1 and guppy version 6.3.8.

Thank you very much.

**Comment by alexomics** [comment]
What operating system or platform are you intending to use? At the moment the [`dev_staging`](https://github.com/LooseLab/readfish/tree/dev_staging) branch is up to date for MinION and GridION. For example I would use the following conda environment:

_readfish_env.yml_:
```yaml
name: readfish
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - pip:
    - git+https://github.com/nanoporetech/read_until_api@v3.0.0
    - ont-pyguppy-client-lib==6.3.8
    - git+https://github.com/LooseLab/readfish@5478d85f3106b6f496279e2ff38d3e172123120a
```

then:

```bash
conda env create -f readfish_env.yml
```

For PromethION the [`guppy_6_minknow_5`](https://github.com/LooseLab/readfish/tree/guppy_6_minknow_5) branch is up to date.
