### ISSUE TITLE
Odd and even field

### ISSUE THREAD

**Issue by ylang0825** [LooseLab/readfish#224]
Hi everyone,
Recently I need to perform a readfish run and a non-adaptive control run on one flowcell simultaneously, eg. readfish run on odd-numbered channels and control run on even-numbered channels. I noticed that the developers had updated a ru/ directory, which seemed to have achieved different operations for odd and even channels. From the code, I tried adding "odd_even = true"  to 'conditions.0' or 'conditions' in the toml file but the 'readfish validate' command told me this was an illegal item. I wonder if this function has been added to the current version of readfish? If not, is there a way to achieve that?

Many thanks!
Lang Yang

**Comment by alexomics** [comment]
The `--odd-even` flag is only available to barcoded experiments at the moment as an experimental feature for control/analysis channels as this was not carried over when I implemented barcode-aware readfish. If you are running `readfish barcode-targets ...` then you can use the `--odd-even` flag with the current version (0.0.11a3, [0ccb593](https://github.com/LooseLab/readfish/commit/0ccb59324906635a0d077f94d7f82388039885cb)) of readfish.

If you are using `readfish targets ...` the way to specify 50% of the flow cell as a control region is by using the experiment TOML like so:

```TOML
[caller_settings]
...

[conditions]
reference = "/path/to/reference.mmi"

[conditions.0]
name = "Control"
control = true
min_chunks = 0
max_chunks = 2
targets = []
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "stop_receiving"
multi_off = "stop_receiving"
no_seq = "stop_receiving"
no_map = "stop_receiving"

[conditions.1]
name = "Analysis"
control = false
min_chunks = 0
max_chunks = 2
targets = ["chr21", "chr22"]
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
no_seq = "proceed"
no_map = "proceed"
```
