### ISSUE TITLE
TOML target specification

### ISSUE THREAD

**Issue by jennieli421** [LooseLab/readfish#242]
If I would like to enrich for all reads that are mapped to a reference, what should I put as `targets`?

**Comment by Adoni5** [comment]
Hi @jennieli421,

I think that would be 

```toml
single_on = "stop_receiving"
multi_on = "stop_receiving"
single_off = "unblock"
multi_off = "unblock"
```

Does that make sense?

**Comment by jennieli421** [comment]
Oh, I meant to ask how I should writ the line of `targets =`.
Should I write `targets = []`?

**Comment by Adoni5** [comment]
Oh I see! What you should do is either list all the chromosome names in the reference like so

`targets = ["chr1", "chr2"...]`

Or you can leave the targets empty, 

`targets = []`

And reverse the toml 

```toml
single_on = "unblock"
multi_on = "unblock"
single_off = "stop_receiving"
multi_off = "stop_receiving"
min_chunks = 0
max_chunks = 2
no_map = "proceed"
no_seq = "proceed"
```

This way anything that maps to the reference is "off target", anything that doesn't map after 2 chunks is unblocked. You may want to change `no_map` to unblock, which means that anything that doesn't map is unblocked immediately rather than left to acquire more chunks.

Hope this helps!
